CALL ..\..\SetGlobalEnvironment.cmd

SET PARENTFOLDER=%GLOBALROOT%\future

SET CMDROOT=%PARENTFOLDER%\cmd
SET SETTINGSROOT=%PARENTFOLDER%\settings
SET RAWDATAFOLDER=%PARENTFOLDER%\rawdata
SET PROCESSEDDATAFOLDER=%PARENTFOLDER%\processeddata
SET TEMPFOLDER=%PARENTFOLDER%\temp