//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyTitle("ParallelCommunicator")]
[assembly: System.Reflection.AssemblyVersion("7.7.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("7.7.541.0")]

// Generated by the MSBuild WriteCodeFragment class on 2015/4/8 15:00:00.

